language: node_js

node_js:
  - "stable"

sudo: required

branches:
  only:
  - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_script:
  - cd angularclient
  - npm install -g @angular/cli
  
script:
  - npm install
  - ng build 
  - ng test -- --no-watch --no-progress
#   - ng e2e -- --protractor-config=e2e/protractor-ci.conf.js
